{{ config(materialized='view') }}

SELECT
    TRANSACTION_ID,
    DATE,
    QUARTER,
    REGION,
    PRODUCT_CATEGORY,
    REVENUE,
    MATERIAL_COST,
    SHIPPING_COST
FROM METRICMIND_DB.RAW_DATA.CLEAN_SALES_TRANSACTIONS